(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const KEY='meadow-pals-v1';
  const APP_VERSION='54';
  const MUSIC=[
    {title:'Calm Playtime',src:'audio/meadow-pals/calm-playtime.mp3'},
    {title:'Cozy Lullaby',src:'audio/meadow-pals/cozy-lullaby.mp3'},
    {title:'Little Steps',src:'audio/meadow-pals/little-steps.mp3'},
    {title:'Sweet Kindergarten',src:'audio/meadow-pals/sweet-kindergarten.mp3'}
  ];
  const meta={
    numbers:{title:'Numbers',kicker:'COUNT WITH PIP',size:11,color:'#dff2e9'},
    letters:{title:'Letters',kicker:'READ WITH POPPY',size:26,color:'#fce2dc'},
    colors:{title:'Colors',kicker:'PAINT WITH DOODLE',size:9,color:'#fff1bf'},
    words:{title:'First Words',kicker:'EXPLORE TOGETHER',size:100,color:'#e6e2f5'}
  };
  const blankProgress=()=>({numbers:{seen:[],views:0},letters:{seen:[],views:0},colors:{seen:[],views:0},words:{seen:[],views:0},sessions:[],minutes:0,lastVisit:null,cursors:{}});
  const newProfile=name=>({id:`p-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,name,created:new Date().toISOString(),progress:blankProgress()});
  let store;
  try{store=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}
  if(!store?.profiles?.length)store={pinHash:'',activeId:'vincent',sound:true,profiles:[{id:'vincent',name:'Vincent',created:new Date().toISOString(),progress:blankProgress()}]};
  store.sound=store.sound!==false;
  store.music=store.music!==false;
  store.musicTrack=Math.max(0,Number(store.musicTrack)||0)%MUSIC.length;
  store.wordLanguage=store.wordLanguage==='es'?'es':'en';
  store.profiles.forEach(p=>{p.progress={...blankProgress(),...(p.progress||{})};Object.keys(meta).forEach(k=>p.progress[k]={seen:[],views:0,...(p.progress[k]||{})});p.progress.sessions=Array.isArray(p.progress.sessions)?p.progress.sessions:[];p.progress.cursors=p.progress.cursors||{}});
  if(!store.profiles.some(p=>p.id===store.activeId))store.activeId=store.profiles[0].id;
  let category='',cards=[],deckTitle='',cardIndex=0,sessionStart=0,touchX=0,pinMode='unlock',parentTab='overview',learningMode='explore',findLocked=false;
  const selectedWordGroups=new Set();
  const active=()=>store.profiles.find(p=>p.id===store.activeId)||store.profiles[0];
  const save=()=>localStorage.setItem(KEY,JSON.stringify(store));
  const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)};
  function go(screen){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===screen));window.scrollTo({top:0,behavior:'smooth'});if(screen==='home')renderHome();if(screen==='profiles')renderProfiles()}
  function renderHome(){const p=active(),spanish=store.wordLanguage==='es';$('#activeName').textContent=p.name;$('#activeAvatar').textContent=p.name.charAt(0).toUpperCase();$('#helloText').textContent=`Hello, ${p.name}!`;if($('#wordPathKicker'))$('#wordPathKicker').textContent=spanish?'APRENDAMOS JUNTOS':'EXPLORE TOGETHER';if($('#wordPathTitle'))$('#wordPathTitle').textContent=spanish?'Primeras palabras':'First Words';if($('#wordPathDetail'))$('#wordPathDetail').textContent=spanish?'Elige uno o más grupos':'Choose a word group'}
  function musicPlayer(){return $('#backgroundMusic')}
  function startMusic(){const audio=musicPlayer();if(!store.music)return pauseMusic();const track=MUSIC[store.musicTrack];if(!audio.src.endsWith(track.src)){audio.src=track.src;audio.load()}audio.volume=.18;audio.play().then(renderSound).catch(renderSound)}
  function pauseMusic(){musicPlayer().pause();renderSound()}
  const voicePlayer=new Audio();
  function synthesizedSpeech(text){if(!('speechSynthesis'in window))return;const music=musicPlayer(),u=new SpeechSynthesisUtterance(text);u.rate=.78;u.pitch=1.08;u.volume=.9;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/Samantha|Ava|Jenny|female/i.test(v.name)&&/^en/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||null;u.onstart=()=>{if(!music.paused)music.volume=.07};u.onend=()=>{music.volume=.18};speechSynthesis.speak(u)}
  function speechFallback(text){if(category==='words'){toast('This Meadow Pal voice is getting ready');return}synthesizedSpeech(text)}
  function speak(text,src){if(!store.sound)return;if('speechSynthesis'in window)window.speechSynthesis.cancel();voicePlayer.pause();voicePlayer.currentTime=0;if(!src)return speechFallback(text);const music=musicPlayer();voicePlayer.src=src;voicePlayer.volume=1;voicePlayer.onplay=()=>{if(!music.paused)music.volume=.07};voicePlayer.onended=()=>{music.volume=.18};voicePlayer.onerror=()=>{music.volume=.18;speechFallback(text)};voicePlayer.play().catch(()=>{music.volume=.18;speechFallback(text)})}
  function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
  function startCategory(key,chosenCards=null,title='',mode='explore'){startMusic();category=key;learningMode=mode;const p=active(),all=chosenCards||window.MEADOW_DATA[key];cards=[...all];if(key==='colors'||key==='words')shuffle(cards);deckTitle=title||meta[key].title;cardIndex=0;sessionStart=Date.now();p.progress.sessions.unshift({category:key,deck:deckTitle,mode,language:key==='words'?store.wordLanguage:'en',date:new Date().toISOString(),cards:cards.length});p.progress.sessions=p.progress.sessions.slice(0,50);save();if(mode==='find'){go('find');renderFindRound()}else{go('learn');renderCard();setTimeout(()=>speakCurrentCard(cards[0]),300)}}
  function cardKey(card){return String(card.word).toLowerCase()}
  function cardLanguage(card){return category==='words'&&store.wordLanguage==='es'&&card.spanish?card.spanish:card}
  function speakCurrentCard(card){const localized=cardLanguage(card);speak(localized.speech,localized.audio)}
  function wordGroupTitle(group){return store.wordLanguage==='es'?(group.spanishTitle||group.title):group.title}
  function recordView(card){const progress=active().progress[category],key=cardKey(card);progress.views++;if(!progress.seen.includes(key))progress.seen.push(key);active().progress.lastVisit=new Date().toISOString();save()}
  function wordGroupFor(word){return Object.values(window.MEADOW_WORD_GROUPS).find(group=>group.words.includes(word))?.title||''}
  function togetherPrompt(card){const group=wordGroupFor(card.word),localized=cardLanguage(card),word=localized.word.toLowerCase();if(store.wordLanguage==='es'){if(group==='Body Parts')return `¿Puedes señalar tu ${word}?`;if(group==='Animals')return `¿Puedes hacer el sonido de ${word}?`;if(group==='Feelings & Describing')return `¿Puedes mostrar ${word}?`;if(group==='Useful Social Words')return `¿Puedes decir “${localized.word}”?`;return `¿Puedes encontrar ${word}?`}if(group==='Body Parts')return `Can you point to your ${word}?`;if(group==='Animals')return `Can you make a ${word} sound?`;if(group==='Feelings & Describing')return `Can you show a ${word} face or action?`;if(group==='Useful Social Words')return `Can you say “${card.word}” together?`;return `Can you find or point to a ${word}?`}
  function renderCard(){const card=cards[cardIndex],localized=cardLanguage(card),m=meta[category],spanish=category==='words'&&store.wordLanguage==='es';$('#learnTitle').textContent=deckTitle||m.title;$('#learnKicker').textContent=learningMode==='together'?(spanish?'APRENDAMOS JUNTOS':'LEARN TOGETHER'):spanish?'PRIMERAS PALABRAS':m.kicker;$('#cardCount').textContent=`${cardIndex+1} ${spanish?'de':'of'} ${cards.length}`;$('#progressBar').style.width=`${(cardIndex+1)/cards.length*100}%`;const picture=$('#cardPicture'),hasArt=Boolean(card.image);picture.classList.toggle('has-art',hasArt);picture.innerHTML=hasArt?`<img src="${esc(card.image)}" alt="" draggable="false">`:esc(card.picture||'');$('#flashCard').classList.toggle('art-card',hasArt);$('#flashCard').classList.toggle('together-card',learningMode==='together');$('#cardWord').textContent=localized.word;$('#cardDetail').textContent=learningMode==='together'?togetherPrompt(card):localized.detail;$('#hearLabel').textContent=spanish?'Escúchalo':'Hear it';$('#flashCard').style.setProperty('--card-color',card.color||m.color);$('#prevCard').disabled=cardIndex===0;$('#prevCard').style.opacity=cardIndex===0?'.4':'1';$('#nextCard').innerHTML=cardIndex===cards.length-1?(spanish?'Terminamos <span>♡</span>':'All done <span>♡</span>'):(spanish?'Siguiente <span>→</span>':'Next card <span>→</span>');$('#flashCard').classList.remove('bump');void $('#flashCard').offsetWidth;$('#flashCard').classList.add('bump');recordView(card)}
  function finishSession(message='Wonderful exploring! ♡'){const mins=Math.max(1,Math.round((Date.now()-sessionStart)/60000));active().progress.minutes+=mins;save();go('home');toast(message)}
  function nextCard(dir=1){if(dir<0&&cardIndex>0){cardIndex--;renderCard();speakCurrentCard(cards[cardIndex]);return}if(dir>0&&cardIndex<cards.length-1){cardIndex++;renderCard();speakCurrentCard(cards[cardIndex]);return}if(dir>0)finishSession(store.wordLanguage==='es'&&category==='words'?'¡Qué bien exploraste! ♡':'Wonderful exploring! ♡')}
  function choiceMarkup(card,correct){const art=card.image?`<img src="${esc(card.image)}" alt="" draggable="false">`:`<span>${esc(card.picture||'')}</span>`;return `<button type="button" class="find-choice" data-find-correct="${correct?'yes':'no'}" aria-label="Picture choice">${art}</button>`}
  function renderFindRound(){findLocked=false;const target=cards[cardIndex],localized=cardLanguage(target),spanish=store.wordLanguage==='es',others=cards.filter(card=>card!==target),distractor=others[Math.floor(Math.random()*others.length)],choices=shuffle([{card:target,correct:true},{card:distractor,correct:false}]);$('#findTitle').textContent=deckTitle;$('#findKicker').textContent=spanish?'ENCUÉNTRALO JUNTOS':'FIND IT TOGETHER';$('#findCount').textContent=`${cardIndex+1} ${spanish?'de':'of'} ${cards.length}`;$('#findProgressBar').style.width=`${(cardIndex+1)/cards.length*100}%`;$('#findLead').textContent=spanish?'¿Puedes encontrar…':'Can you find…';$('#findWord').textContent=`${localized.word}?`;$('#findFeedback').textContent=spanish?'Toca una imagen':'Tap a picture';$('#findChoices').innerHTML=choices.map(choice=>choiceMarkup(choice.card,choice.correct)).join('');$$('[data-find-correct]').forEach(button=>button.onclick=()=>chooseFind(button));setTimeout(()=>speakCurrentCard(target),250)}
  function chooseFind(button){if(findLocked)return;const spanish=store.wordLanguage==='es';if(button.dataset.findCorrect!=='yes'){button.classList.add('try-again');$('#findFeedback').textContent=spanish?'Mira otra vez ♡':'Take another look ♡';setTimeout(()=>button.classList.remove('try-again'),450);return}findLocked=true;button.classList.add('found');const target=cards[cardIndex];$('#findFeedback').textContent=spanish?'¡Lo encontraste! ♡':'You found it! ♡';recordView(target);speakCurrentCard(target);setTimeout(()=>{if(cardIndex<cards.length-1){cardIndex++;renderFindRound()}else finishSession(spanish?'¡Qué bien encontraste! ♡':'Wonderful finding! ♡')},900)}
  function renderProfiles(){const p=active();$('#profileGrid').innerHTML=store.profiles.map(profile=>`<button class="profile-choice ${profile.id===p.id?'selected':''}" data-profile="${profile.id}"><span>${esc(profile.name.charAt(0).toUpperCase())}</span><strong>${esc(profile.name)}</strong><small>${profile.id===p.id?'Learning now':'Tap to choose'}</small></button>`).join('');$$('[data-profile]').forEach(b=>b.onclick=()=>{store.activeId=b.dataset.profile;save();renderProfiles();renderHome();toast(`${active().name} is ready!`)})}
  async function hash(value){const bytes=new TextEncoder().encode(`meadow:${value}`),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
  function openPin(){pinMode=store.pinHash?'unlock':'create';$('#pinTitle').textContent=pinMode==='create'?'Create a parent PIN':'Parent Hub';$('#pinHelp').textContent=pinMode==='create'?'Choose 4 numbers that only grown-ups know.':'Enter your 4-digit PIN.';$('#pinInput').value='';$('#pinError').textContent='';updateDots();$('#pinModal').hidden=false;setTimeout(()=>$('#pinInput').focus(),50)}
  function updateDots(){$$('#pinDots i').forEach((d,i)=>d.classList.toggle('filled',i<$('#pinInput').value.length))}
  function openParentHub(){parentTab='overview';$('#parentHub').hidden=false;$$('[data-parent-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.parentTab===parentTab));renderParent()}
  const totals=p=>Object.fromEntries(Object.keys(meta).map(k=>[k,{seen:p.progress[k].seen.length,total:window.MEADOW_DATA[k].length,views:p.progress[k].views}]));
  function renderParent(){const root=$('#parentContent'),p=active(),t=totals(p);if(parentTab==='overview')root.innerHTML=`<div class="parent-welcome"><div><p class="eyebrow">LEARNING SNAPSHOT</p><h2>${esc(p.name)} is exploring beautifully.</h2><p>Progress here is descriptive, not a score. Repetition is healthy toddler learning.</p></div><div class="date-chip">Updated ${p.progress.lastVisit?new Date(p.progress.lastVisit).toLocaleDateString():'today'}</div></div><div class="stat-grid"><div class="stat"><span>CARDS EXPLORED</span><strong>${Object.values(t).reduce((n,x)=>n+x.views,0)}</strong><small>all-time views</small></div><div class="stat"><span>WORDS MET</span><strong>${t.words.seen}<small> / 100</small></strong><small>unique picture words</small></div><div class="stat"><span>LEARNING TIME</span><strong>${p.progress.minutes}<small> min</small></strong><small>approximate</small></div><div class="stat"><span>RECENT VISITS</span><strong>${p.progress.sessions.length}</strong><small>mini-sessions</small></div></div><div class="parent-panel"><h3>Recent activity</h3>${recentMarkup(p)}</div>`;
    if(parentTab==='learning')root.innerHTML=`<div class="parent-welcome"><div><p class="eyebrow">EXPOSURE BY AREA</p><h2>What ${esc(p.name)} has seen</h2><p>“Seen” means the card appeared at least once; it does not imply mastery.</p></div></div><div class="parent-panel">${Object.keys(meta).map(k=>{const x=t[k],pct=Math.round(x.seen/x.total*100);return `<div class="skill-row"><div><strong>${meta[k].title}</strong><small>${x.views} card views</small></div><div class="skill-meter"><i style="width:${pct}%"></i></div><b>${x.seen}/${x.total}</b></div>`}).join('')}</div><div class="parent-panel"><h3>Gentle ideas for next time</h3><p>${suggestion(t)}</p></div>`;
    if(parentTab==='profiles')root.innerHTML=`<div class="parent-welcome"><div><p class="eyebrow">LEARNER PROFILES</p><h2>Children on this device</h2><p>Learning history stays separate for each child.</p></div></div><div class="parent-panel">${store.profiles.map(x=>`<div class="manage-profile"><div><strong>${esc(x.name)}</strong><br><small>${x.id===store.activeId?'Active learner':`${x.progress.sessions.length} sessions`}</small></div><div><button data-switch="${x.id}">Choose</button> ${store.profiles.length>1?`<button class="danger" data-delete="${x.id}">Delete</button>`:''}</div></div>`).join('')}</div><div class="parent-actions"><button id="parentAddProfile">＋ Add learner</button></div>`;
    if(parentTab==='settings')root.innerHTML=`<div class="parent-welcome"><div><p class="eyebrow">SETTINGS & PRIVACY</p><h2>A calm, private learning space</h2><p>All learning data is stored locally in this browser.</p></div></div><div class="parent-panel"><div class="setting-row"><div><strong>Spoken card names</strong><br><small>Use Meadow Pals character voices when available</small></div><input type="checkbox" id="parentSound" ${store.sound?'checked':''}></div><div class="setting-row"><div><strong>Gentle background music</strong><br><small>Four supplied songs rotate automatically at a quiet volume</small></div><input type="checkbox" id="parentMusic" ${store.music?'checked':''}></div><div class="setting-row"><div><strong>Now in the rotation</strong><br><small>${esc(MUSIC[store.musicTrack].title)}</small></div><button class="tiny" id="nextTrack">Next song</button></div></div><div class="parent-panel"><h3>App update</h3><div class="setting-row"><div><strong>Meadow Pals version ${APP_VERSION}</strong><br><small>Check for the newest published lessons and artwork</small></div><button class="tiny" id="checkUpdate">Update app</button></div></div><div class="parent-panel"><h3>Data controls</h3><div class="parent-actions"><button id="exportData">Download learning data</button><button id="changePin">Change PIN</button><button class="danger" id="resetProgress">Reset ${esc(p.name)}'s progress</button></div></div>`;
    wireParent()}
  function recentMarkup(p){const sessions=p.progress.sessions.slice(0,6);return sessions.length?sessions.map(s=>`<div class="activity-row"><div><strong>${esc(s.deck||meta[s.category]?.title||'Learning')}</strong><small>${new Date(s.date).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div><b>${s.cards} cards</b></div>`).join(''):'<p>No learning sessions yet. The first cards Vincent explores will appear here.</p>'}
  function suggestion(t){const next=Object.entries(t).sort((a,b)=>(a[1].seen/a[1].total)-(b[1].seen/b[1].total))[0]?.[0]||'words';return `Try a short ${meta[next].title.toLowerCase()} set together. Point to the picture, say the word slowly, and let your child decide when to move on.`}
  async function checkForUpdate(){const button=$('#checkUpdate');if(button){button.disabled=true;button.textContent='Checking…'}try{if(!('serviceWorker'in navigator)){toast('Updates are not available in this browser');return}const reg=await navigator.serviceWorker.getRegistration()||await navigator.serviceWorker.register(`sw.js?v=${APP_VERSION}`);await reg.update();toast(reg.waiting||reg.installing?'Update found — refreshing shortly':'Meadow Pals is up to date')}catch{toast('Could not check for an update')}finally{if(button){button.disabled=false;button.textContent='Update app'}}}
  function wireParent(){$$('[data-switch]').forEach(b=>b.onclick=()=>{store.activeId=b.dataset.switch;save();renderHome();renderParent();toast(`${active().name} selected`)});$$('[data-delete]').forEach(b=>b.onclick=()=>{const p=store.profiles.find(x=>x.id===b.dataset.delete);if(!p||!confirm(`Delete ${p.name}'s profile and learning history?`))return;store.profiles=store.profiles.filter(x=>x.id!==p.id);if(store.activeId===p.id)store.activeId=store.profiles[0].id;save();renderHome();renderParent()});$('#parentAddProfile')?.addEventListener('click',()=>{$('#nameModal').hidden=false;setTimeout(()=>$('#newName').focus(),50)});$('#parentSound')?.addEventListener('change',e=>{store.sound=e.target.checked;save();renderSound()});$('#parentMusic')?.addEventListener('change',e=>{store.music=e.target.checked;save();store.music?startMusic():pauseMusic()});$('#nextTrack')?.addEventListener('click',()=>{store.musicTrack=(store.musicTrack+1)%MUSIC.length;save();startMusic();renderParent();toast(`Now playing ${MUSIC[store.musicTrack].title}`)});$('#checkUpdate')?.addEventListener('click',checkForUpdate);$('#exportData')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meadow-pals-learning-data.json';a.click();URL.revokeObjectURL(a.href)});$('#changePin')?.addEventListener('click',()=>{store.pinHash='';save();$('#parentHub').hidden=true;openPin()});$('#resetProgress')?.addEventListener('click',()=>{if(!confirm(`Reset all of ${active().name}'s learning history?`))return;active().progress=blankProgress();save();renderParent();toast('Learning history reset')})}
  function renderSound(){const audio=musicPlayer();$('#soundToggle').textContent=store.sound?'🔊':'🔇';$('#musicToggle').textContent=store.music?'♫':'♩';$('#musicToggle').classList.toggle('playing',store.music&&!audio.paused);$('#musicToggle').title=store.music?`Music on · ${MUSIC[store.musicTrack].title}`:'Music off'}
  $$('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));$$('[data-category]').forEach(b=>b.onclick=()=>startCategory(b.dataset.category));
  function renderWordGroupPicker(){const groups=window.MEADOW_WORD_GROUPS,spanish=store.wordLanguage==='es',allSelected=selectedWordGroups.size===Object.keys(groups).length;$$('[data-word-language]').forEach(button=>{const selected=button.dataset.wordLanguage===store.wordLanguage;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',selected)});$('#wordModalEyebrow').textContent=spanish?'PRIMERAS PALABRAS':'FIRST WORDS';$('#wordModalTitle').textContent=spanish?'¿Qué vamos a explorar?':'What shall we explore?';$('#wordModalHelp').textContent=spanish?'Elige un grupo o combina todos los que quieras.':'Choose one group or combine as many as you like.';$('#wordModeEyebrow').textContent=spanish?'¿CÓMO VAMOS A JUGAR?':'HOW SHALL WE PLAY?';const modeCopy=spanish?{explore:['Explorar','Mira y escucha'],together:['Juntos','Preguntas para compartir'],find:['Encuéntralo','Elige la imagen']}:{explore:['Explore','See and hear cards'],together:['Together','Grown-up prompts'],find:['Find It','Choose the picture']};$$('[data-word-mode]').forEach(button=>{button.querySelector('strong').textContent=modeCopy[button.dataset.wordMode][0];button.querySelector('small').textContent=modeCopy[button.dataset.wordMode][1]});$('#wordGroupGrid').innerHTML=Object.entries(groups).map(([id,group])=>`<button type="button" class="${selectedWordGroups.has(id)?'selected':''}" aria-pressed="${selectedWordGroups.has(id)}" data-word-group="${esc(id)}"><span>${esc(group.icon)}</span><strong>${esc(wordGroupTitle(group))}</strong><small>${group.words.length} ${spanish?'palabras':'words'}</small></button>`).join('')+`<button type="button" class="${allSelected?'selected':''}" aria-pressed="${allSelected}" data-word-group="all"><span>✨</span><strong>${spanish?'Todas las palabras':'All First Words'}</strong><small>100 ${spanish?'palabras':'words'}</small></button>`;$$('[data-word-group]').forEach(button=>button.onclick=()=>toggleWordGroup(button.dataset.wordGroup));const count=[...selectedWordGroups].reduce((sum,id)=>sum+groups[id].words.length,0),start=$('#startWordGroups');start.disabled=!count;start.textContent=count?(spanish?`Empezar con ${count} palabra${count===1?'':'s'}`:`Start with ${count} word${count===1?'':'s'}`):(spanish?'Elige al menos un grupo':'Choose at least one group')}
  function toggleWordGroup(id){const keys=Object.keys(window.MEADOW_WORD_GROUPS);if(id==='all'){if(selectedWordGroups.size===keys.length)selectedWordGroups.clear();else keys.forEach(key=>selectedWordGroups.add(key))}else if(selectedWordGroups.has(id))selectedWordGroups.delete(id);else selectedWordGroups.add(id);renderWordGroupPicker()}
  $('#openWordGroups').onclick=()=>{renderWordGroupPicker();$('#wordGroupModal').hidden=false};$$('[data-word-language]').forEach(button=>button.onclick=()=>{store.wordLanguage=button.dataset.wordLanguage;save();renderHome();renderWordGroupPicker()});$$('[data-word-mode]').forEach(button=>button.onclick=()=>{learningMode=button.dataset.wordMode;$$('[data-word-mode]').forEach(choice=>choice.classList.toggle('selected',choice===button))});$('#startWordGroups').onclick=()=>{const groups=window.MEADOW_WORD_GROUPS,ids=[...selectedWordGroups],chosenWords=new Set(ids.flatMap(id=>groups[id].words)),selected=window.MEADOW_DATA.words.filter(card=>chosenWords.has(card.word)),spanish=store.wordLanguage==='es',title=ids.length===1?wordGroupTitle(groups[ids[0]]):ids.length===Object.keys(groups).length?(spanish?'Primeras palabras':'First Words'):(spanish?`${ids.length} grupos de palabras`:`${ids.length} Word Groups`);if(!selected.length)return;$('#wordGroupModal').hidden=true;startCategory('words',selected,title,learningMode)};
  $('#profilePicker').onclick=()=>go('profiles');$('#addProfile').onclick=()=>{$('#nameModal').hidden=false;setTimeout(()=>$('#newName').focus(),50)};
  $('#nameForm').onsubmit=e=>{e.preventDefault();const name=$('#newName').value.trim();if(!name)return;const p=newProfile(name);store.profiles.push(p);store.activeId=p.id;save();$('#newName').value='';$('#nameModal').hidden=true;renderHome();if(!$('#parentHub').hidden)renderParent();else go('profiles');toast(`${name} is ready to learn!`)};
  $('#openParent').onclick=openPin;$('#pinInput').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,4);updateDots()};$('#pinForm').onclick=()=>$('#pinInput').focus();
  $('#pinForm').onsubmit=async e=>{e.preventDefault();const val=$('#pinInput').value;if(val.length!==4){$('#pinError').textContent='Please enter 4 numbers.';return}const digest=await hash(val);if(pinMode==='create'){store.pinHash=digest;save();$('#pinModal').hidden=true;openParentHub();toast('Parent PIN created')}else if(digest===store.pinHash){$('#pinModal').hidden=true;openParentHub()}else{$('#pinError').textContent='That PIN did not match. Try again.';$('#pinInput').value='';updateDots()}};
  $$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal-layer').hidden=true);$('#closeParent').onclick=()=>{$('#parentHub').hidden=true;renderHome()};$$('[data-parent-tab]').forEach(b=>b.onclick=()=>{parentTab=b.dataset.parentTab;$$('[data-parent-tab]').forEach(x=>x.classList.toggle('selected',x===b));renderParent()});
  $('#soundToggle').onclick=()=>{store.sound=!store.sound;save();renderSound();if(store.sound){const prior=category;category='';speak('Hello!');category=prior}};$('#musicToggle').onclick=()=>{store.music=!store.music;save();store.music?startMusic():pauseMusic();toast(store.music?'Gentle music on':'Music paused')};$('#speakCard').onclick=()=>speakCurrentCard(cards[cardIndex]);$('#speakFind').onclick=()=>speakCurrentCard(cards[cardIndex]);$('#hearWord').onclick=e=>{e.stopPropagation();speakCurrentCard(cards[cardIndex])};$('#flashCard').onclick=()=>speakCurrentCard(cards[cardIndex]);$('#flashCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();speakCurrentCard(cards[cardIndex])}};$('#nextCard').onclick=()=>nextCard(1);$('#prevCard').onclick=()=>nextCard(-1);$('#flashCard').ontouchstart=e=>touchX=e.touches[0].clientX;$('#flashCard').ontouchend=e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>60)nextCard(d<0?1:-1)};musicPlayer().onended=()=>{store.musicTrack=(store.musicTrack+1)%MUSIC.length;save();startMusic()};musicPlayer().onplay=renderSound;musicPlayer().onpause=renderSound;
  renderHome();renderSound();save();if('serviceWorker'in navigator){let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});navigator.serviceWorker.register(`sw.js?v=${APP_VERSION}`).catch(()=>{})}
})();
