const NUMBER_CARDS = [
  {word:'0',speech:'Zero',character:'pip',image:'assets/meadow-pals/numbers/0-empty-basket.png',audio:'audio/voice-packs/pip/numbers/001-0.mp3',detail:'An empty basket means zero.',spanish:{word:'0',speech:'Cero',detail:'Una canasta vacía significa cero.',audio:''}},
  {word:'1',speech:'One',character:'pip',image:'assets/meadow-pals/numbers/1-apple.png',audio:'audio/voice-packs/pip/numbers/002-1.mp3',detail:'Pip is holding one apple.',spanish:{word:'1',speech:'Uno',detail:'Pip sostiene una manzana.',audio:''}},
  {word:'2',speech:'Two',character:'poppy',image:'assets/meadow-pals/numbers/2-birds.png',audio:'audio/voice-packs/poppy/numbers/003-2.mp3',detail:'Poppy found two birds.',spanish:{word:'2',speech:'Dos',detail:'Poppy encontró dos pájaros.',audio:''}},
  {word:'3',speech:'Three',character:'doodle',image:'assets/meadow-pals/numbers/3-ducklings.png',audio:'audio/voice-packs/doodle/numbers/004-3.mp3',detail:'Three ducklings are together.',spanish:{word:'3',speech:'Tres',detail:'Hay tres patitos juntos.',audio:''}},
  {word:'4',speech:'Four',character:'pip',image:'assets/meadow-pals/numbers/4-blocks.png',audio:'audio/voice-packs/pip/numbers/005-4.mp3',detail:'Pip has four blocks.',spanish:{word:'4',speech:'Cuatro',detail:'Pip tiene cuatro bloques.',audio:''}},
  {word:'5',speech:'Five',character:'poppy',image:'assets/meadow-pals/numbers/5-flowers.png',audio:'audio/voice-packs/poppy/numbers/006-5.mp3',detail:'Poppy sees five flowers.',spanish:{word:'5',speech:'Cinco',detail:'Poppy ve cinco flores.',audio:''}},
  {word:'6',speech:'Six',character:'doodle',image:'assets/meadow-pals/numbers/6-bubbles.png',audio:'audio/voice-packs/doodle/numbers/007-6.mp3',detail:'Doodle counts six bubbles.',spanish:{word:'6',speech:'Seis',detail:'Doodle cuenta seis burbujas.',audio:''}},
  {word:'7',speech:'Seven',character:'pip',image:'assets/meadow-pals/numbers/7-strawberries.png',audio:'audio/voice-packs/pip/numbers/008-7.mp3',detail:'Pip found seven strawberries.',spanish:{word:'7',speech:'Siete',detail:'Pip encontró siete fresas.',audio:''}},
  {word:'8',speech:'Eight',character:'poppy',image:'assets/meadow-pals/numbers/8-balloons.png',audio:'audio/voice-packs/poppy/numbers/009-8.mp3',detail:'Poppy has eight balloons.',spanish:{word:'8',speech:'Ocho',detail:'Poppy tiene ocho globos.',audio:''}},
  {word:'9',speech:'Nine',character:'doodle',image:'assets/meadow-pals/numbers/9-balls.png',audio:'audio/voice-packs/doodle/numbers/010-9.mp3',detail:'Doodle counts nine balls.',spanish:{word:'9',speech:'Nueve',detail:'Doodle cuenta nueve pelotas.',audio:''}},
  {word:'10',speech:'Ten',character:'pip',image:'assets/meadow-pals/numbers/10-stars.png',audio:'audio/voice-packs/pip/numbers/011-10.mp3',detail:'The pals found ten stars!',spanish:{word:'10',speech:'Diez',detail:'¡Los amigos encontraron diez estrellas!',audio:''}}
];

const WORD_ASSETS = {
  Head:{image:'assets/meadow-pals/words/body-parts/head.png',character:'pip'},
  Eyes:{image:'assets/meadow-pals/words/body-parts/eyes.png',character:'poppy'},
  Nose:{image:'assets/meadow-pals/words/body-parts/nose.png',character:'pip'},
  Mouth:{image:'assets/meadow-pals/words/body-parts/mouth.png',character:'pip'},
  Ears:{image:'assets/meadow-pals/words/body-parts/ears.png',character:'poppy'},
  Hands:{image:'assets/meadow-pals/words/body-parts/hands.png',character:'poppy'},
  Feet:{image:'assets/meadow-pals/words/body-parts/feet.png',character:'doodle'},
  Tummy:{image:'assets/meadow-pals/words/body-parts/tummy.png',character:'doodle'},
  Hair:{image:'assets/meadow-pals/words/body-parts/hair.png',character:'pip'},
  Teeth:{image:'assets/meadow-pals/words/body-parts/teeth.png',character:'poppy'},
  Dog:{image:'assets/meadow-pals/words/animals/dog.png',character:'pip'},
  Cat:{image:'assets/meadow-pals/words/animals/cat.png',character:'poppy'},
  Bird:{image:'assets/meadow-pals/words/animals/bird.png',character:'poppy'},
  Fish:{image:'assets/meadow-pals/words/animals/fish.png',character:'doodle'},
  Duck:{image:'assets/meadow-pals/words/animals/duck.png',character:'doodle'},
  Bear:{image:'assets/meadow-pals/words/animals/bear.png',character:'pip'},
  Bunny:{image:'assets/meadow-pals/words/animals/bunny.png',character:'poppy'},
  Cow:{image:'assets/meadow-pals/words/animals/cow.png',character:'pip'},
  Pig:{image:'assets/meadow-pals/words/animals/pig.png',character:'poppy'},
  Horse:{image:'assets/meadow-pals/words/animals/horse.png',character:'pip'},
  Lion:{image:'assets/meadow-pals/words/animals/lion.png',character:'pip'},
  Monkey:{image:'assets/meadow-pals/words/animals/monkey.png',character:'doodle'},
  Frog:{image:'assets/meadow-pals/words/animals/frog.png',character:'doodle'},
  Bug:{image:'assets/meadow-pals/words/animals/bug.png',character:'poppy'},
  Butterfly:{image:'assets/meadow-pals/words/animals/butterfly.png',character:'poppy'},
  Apple:{image:'assets/meadow-pals/words/food-drink/apple.png',character:'pip'},
  Banana:{image:'assets/meadow-pals/words/food-drink/banana.png',character:'doodle'},
  Orange:{image:'assets/meadow-pals/words/food-drink/orange.png',character:'poppy'},
  Berry:{image:'assets/meadow-pals/words/food-drink/berry.png',character:'pip'},
  Milk:{image:'assets/meadow-pals/words/food-drink/milk.png',character:'doodle'},
  Water:{image:'assets/meadow-pals/words/food-drink/water.png',character:'poppy'},
  Bread:{image:'assets/meadow-pals/words/food-drink/bread.png',character:'pip'},
  Cheese:{image:'assets/meadow-pals/words/food-drink/cheese.png',character:'doodle'},
  Egg:{image:'assets/meadow-pals/words/food-drink/egg.png',character:'poppy'},
  Cookie:{image:'assets/meadow-pals/words/food-drink/cookie.png',character:'doodle'},
  Happy:{image:'assets/meadow-pals/words/feelings-describing/happy.png',character:'doodle'},
  Sad:{image:'assets/meadow-pals/words/feelings-describing/sad.png',character:'poppy'},
  Mad:{image:'assets/meadow-pals/words/feelings-describing/mad.png',character:'pip'},
  Sleepy:{image:'assets/meadow-pals/words/feelings-describing/sleepy.png',character:'doodle'},
  Hungry:{image:'assets/meadow-pals/words/feelings-describing/hungry.png',character:'pip'},
  Big:{image:'assets/meadow-pals/words/feelings-describing/big.png',character:'pip'},
  Little:{image:'assets/meadow-pals/words/feelings-describing/little.png',character:'doodle'},
  Hot:{image:'assets/meadow-pals/words/feelings-describing/hot.png',character:'poppy'},
  Cold:{image:'assets/meadow-pals/words/feelings-describing/cold.png',character:'pip'},
  Gentle:{image:'assets/meadow-pals/words/feelings-describing/gentle.png',character:'poppy'},
  Mommy:{image:'assets/meadow-pals/words/people/mommy.png',character:'poppy'},
  Daddy:{image:'assets/meadow-pals/words/people/daddy.png',character:'pip'},
  Baby:{image:'assets/meadow-pals/words/people/baby.png',character:'doodle'},
  Family:{image:'assets/meadow-pals/words/people/family.png',character:'pip'},
  Friend:{image:'assets/meadow-pals/words/people/friend.png',character:'poppy'},
  Car:{image:'assets/meadow-pals/words/things-that-go/car.png',character:'pip'},
  Truck:{image:'assets/meadow-pals/words/things-that-go/truck.png',character:'poppy'},
  Train:{image:'assets/meadow-pals/words/things-that-go/train.png',character:'doodle'},
  Boat:{image:'assets/meadow-pals/words/things-that-go/boat.png',character:'poppy'},
  Plane:{image:'assets/meadow-pals/words/things-that-go/plane.png',character:'pip'},
  Ball:{image:'assets/meadow-pals/words/toys-play/ball.png',character:'doodle'},
  Book:{image:'assets/meadow-pals/words/toys-play/book.png',character:'poppy'},
  Bike:{image:'assets/meadow-pals/words/toys-play/bike.png',character:'pip'},
  Doll:{image:'assets/meadow-pals/words/toys-play/doll.png',character:'poppy'},
  Blocks:{image:'assets/meadow-pals/words/toys-play/blocks.png',character:'doodle'},
  Sun:{image:'assets/meadow-pals/words/nature-weather/sun.png',character:'doodle'},
  Moon:{image:'assets/meadow-pals/words/nature-weather/moon.png',character:'poppy'},
  Star:{image:'assets/meadow-pals/words/nature-weather/star.png',character:'pip'},
  Cloud:{image:'assets/meadow-pals/words/nature-weather/cloud.png',character:'doodle'},
  Rain:{image:'assets/meadow-pals/words/nature-weather/rain.png',character:'poppy'},
  Snow:{image:'assets/meadow-pals/words/nature-weather/snow.png',character:'pip'},
  Tree:{image:'assets/meadow-pals/words/nature-weather/tree.png',character:'pip'},
  Flower:{image:'assets/meadow-pals/words/nature-weather/flower.png',character:'poppy'},
  Grass:{image:'assets/meadow-pals/words/nature-weather/grass.png',character:'doodle'},
  Sky:{image:'assets/meadow-pals/words/nature-weather/sky.png',character:'poppy'},
  Hi:{image:'assets/meadow-pals/words/useful-social/hi.png',character:'poppy'},
  Bye:{image:'assets/meadow-pals/words/useful-social/bye.png',character:'doodle'},
  Yes:{image:'assets/meadow-pals/words/useful-social/yes.png',character:'pip'},
  No:{image:'assets/meadow-pals/words/useful-social/no.png',character:'poppy'},
  Please:{image:'assets/meadow-pals/words/useful-social/please.png',character:'doodle'},
  Thanks:{image:'assets/meadow-pals/words/useful-social/thanks.png',character:'poppy'},
  More:{image:'assets/meadow-pals/words/useful-social/more.png',character:'pip'},
  'All done':{image:'assets/meadow-pals/words/useful-social/all-done.png',character:'doodle'},
  Help:{image:'assets/meadow-pals/words/useful-social/help.png',character:'pip'},
  Love:{image:'assets/meadow-pals/words/useful-social/love.png',character:'poppy'},
  Cup:{image:'assets/meadow-pals/words/home-everyday/cup.png',character:'pip'},
  Spoon:{image:'assets/meadow-pals/words/home-everyday/spoon.png',character:'doodle'},
  Plate:{image:'assets/meadow-pals/words/home-everyday/plate.png',character:'poppy'},
  Chair:{image:'assets/meadow-pals/words/home-everyday/chair.png',character:'pip'},
  Bed:{image:'assets/meadow-pals/words/home-everyday/bed.png',character:'doodle'},
  Bath:{image:'assets/meadow-pals/words/home-everyday/bath.png',character:'poppy'},
  Door:{image:'assets/meadow-pals/words/home-everyday/door.png',character:'pip'},
  Light:{image:'assets/meadow-pals/words/home-everyday/light.png',character:'doodle'},
  Clock:{image:'assets/meadow-pals/words/home-everyday/clock.png',character:'poppy'},
  Phone:{image:'assets/meadow-pals/words/home-everyday/phone.png',character:'pip'},
  Shirt:{image:'assets/meadow-pals/words/clothing/shirt.png',character:'pip'},
  Pants:{image:'assets/meadow-pals/words/clothing/pants.png',character:'doodle'},
  Shoes:{image:'assets/meadow-pals/words/clothing/shoes.png',character:'poppy'},
  Socks:{image:'assets/meadow-pals/words/clothing/socks.png',character:'doodle'},
  Hat:{image:'assets/meadow-pals/words/clothing/hat.png',character:'pip'},
  Coat:{image:'assets/meadow-pals/words/clothing/coat.png',character:'poppy'},
  Dress:{image:'assets/meadow-pals/words/clothing/dress.png',character:'poppy'},
  Pajamas:{image:'assets/meadow-pals/words/clothing/pajamas.png',character:'doodle'},
  Diaper:{image:'assets/meadow-pals/words/clothing/diaper.png',character:'doodle'},
  Boots:{image:'assets/meadow-pals/words/clothing/boots.png',character:'pip'}
};

const wordSlug=value=>value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'card';

const SPANISH_FIRST_WORDS = [
  'Mamá','Papá','Bebé','Familia','Amigo','Perro','Gato','Pájaro','Pez','Pato',
  'Oso','Conejo','Vaca','Cerdo','Caballo','León','Mono','Rana','Insecto','Mariposa',
  'Pelota','Libro','Carro','Camión','Tren','Barco','Avión','Bicicleta','Muñeca','Bloques',
  'Vaso','Cuchara','Plato','Silla','Cama','Baño','Puerta','Luz','Reloj','Teléfono',
  'Manzana','Banana','Naranja','Fresa','Leche','Agua','Pan','Queso','Huevo','Galleta',
  'Cabeza','Ojos','Nariz','Boca','Orejas','Manos','Pies','Barriga','Pelo','Dientes',
  'Camisa','Pantalones','Zapatos','Calcetines','Sombrero','Abrigo','Vestido','Pijama','Pañal','Botas',
  'Sol','Luna','Estrella','Nube','Lluvia','Nieve','Árbol','Flor','Pasto','Cielo',
  'Hola','Adiós','Sí','No','Por favor','Gracias','Más','Se acabó','Ayuda','Amor',
  'Feliz','Triste','Enojado','Con sueño','Con hambre','Grande','Pequeño','Caliente','Frío','Suave'
];

const LETTER_EXAMPLES = [
  ['A','Apple','assets/meadow-pals/words/food-drink/apple.png'],
  ['B','Bear','assets/meadow-pals/words/animals/bear.png'],
  ['C','Cat','assets/meadow-pals/words/animals/cat.png'],
  ['D','Dog','assets/meadow-pals/words/animals/dog.png'],
  ['E','Egg','assets/meadow-pals/words/food-drink/egg.png'],
  ['F','Frog','assets/meadow-pals/words/animals/frog.png'],
  ['G','Grass','assets/meadow-pals/words/nature-weather/grass.png'],
  ['H','Hat','assets/meadow-pals/words/clothing/hat.png'],
  ['I','Ice cream','assets/meadow-pals/letters/i-ice-cream.png'],
  ['J','Juice','assets/meadow-pals/letters/j-juice.png'],
  ['K','Key','assets/meadow-pals/letters/k-key.png'],
  ['L','Lion','assets/meadow-pals/words/animals/lion.png'],
  ['M','Moon','assets/meadow-pals/words/nature-weather/moon.png'],
  ['N','Nose','assets/meadow-pals/words/body-parts/nose.png'],
  ['O','Orange','assets/meadow-pals/words/food-drink/orange.png'],
  ['P','Pig','assets/meadow-pals/words/animals/pig.png'],
  ['Q','Queen','assets/meadow-pals/letters/q-queen.png'],
  ['R','Rain','assets/meadow-pals/words/nature-weather/rain.png'],
  ['S','Sun','assets/meadow-pals/words/nature-weather/sun.png'],
  ['T','Tree','assets/meadow-pals/words/nature-weather/tree.png'],
  ['U','Umbrella','assets/meadow-pals/words/nature-weather/rain.png'],
  ['V','Violin','assets/meadow-pals/letters/v-violin.png'],
  ['W','Water','assets/meadow-pals/words/food-drink/water.png'],
  ['X','Box','assets/meadow-pals/letters/x-box.png'],
  ['Y','Yes','assets/meadow-pals/words/useful-social/yes.png'],
  ['Z','Zebra','assets/meadow-pals/letters/z-zebra.png']
];

const LETTER_AUDIO_REFRESH = new Set(['G','H','L','N','R','T','W','Y']);
const LETTER_CARDS = LETTER_EXAMPLES.map(([letter,example,image],index)=>({
  word:letter,
  image,
  detail:`${letter} is for ${example.toLowerCase()}`,
  speech:`${letter}. ${example}`,
  audio:`audio/voice-packs/poppy/letters/${String(index+1).padStart(3,'0')}-${letter.toLowerCase()}${LETTER_AUDIO_REFRESH.has(letter)?'-refresh':''}.mp3`
}));

const COLOR_CARDS = [
  ['Red','Rojo','#ef5d5d','red'],['Orange','Naranja','#f59c45','orange'],['Yellow','Amarillo','#f6cf4a','yellow'],
  ['Pink','Rosa','#f49abb','pink'],['Purple','Morado','#9b79d1','purple'],['Green','Verde','#70b978','green'],
  ['Blue','Azul','#5b9bd5','blue'],['Black','Negro','#343643','black'],['Brown','Marrón','#95664b','brown']
].map(([word,spanishWord,color,slug],index)=>({word,image:`assets/meadow-pals/colors/${slug}.png`,character:'doodle',detail:`${word} is a wonderful color`,color,speech:word,audio:`audio/voice-packs/doodle/colors/${String(index+1).padStart(3,'0')}-${slug}.mp3`,spanish:{word:spanishWord,detail:`${spanishWord} es un color maravilloso`,speech:spanishWord,audio:''}}));

const SHAPE_CARDS = [
  ['Circle','Círculo','circle','A ball is shaped like a circle','Una pelota tiene forma de círculo'],
  ['Square','Cuadrado','square','A block has a square face','Un bloque tiene una cara cuadrada'],
  ['Triangle','Triángulo','triangle','A sandwich can be a triangle','Un sándwich puede ser un triángulo'],
  ['Rectangle','Rectángulo','rectangle','A picture frame can be a rectangle','Un marco puede ser un rectángulo'],
  ['Oval','Óvalo','oval','An egg is shaped like an oval','Un huevo tiene forma de óvalo'],
  ['Diamond','Rombo','diamond','A kite can be a diamond','Una cometa puede tener forma de rombo'],
  ['Star','Estrella','star','A star has five bright points','Una estrella tiene cinco puntas brillantes'],
  ['Heart','Corazón','heart','A heart is a loving shape','Un corazón es una forma llena de amor'],
  ['Crescent','Media luna','crescent','The moon can look like a crescent','La luna puede verse como una media luna']
].map(([word,spanishWord,slug,detail,spanishDetail],index)=>{const character=['doodle','pip','poppy'][index%3];return {word,image:`assets/meadow-pals/shapes/${slug}.png`,character,detail,speech:word,audio:`audio/voice-packs/${character}/shapes/${String(index+1).padStart(3,'0')}-${slug}.mp3`,spanish:{word:spanishWord,detail:spanishDetail,speech:spanishWord,audio:''}}});

const SPANISH_LETTER_EXAMPLES = [
  ['A','Agua','assets/meadow-pals/words/food-drink/water.png'],
  ['B','Bebé','assets/meadow-pals/words/people/baby.png'],
  ['C','Caballo','assets/meadow-pals/words/animals/horse.png'],
  ['D','Dientes','assets/meadow-pals/words/body-parts/teeth.png'],
  ['E','Estrella','assets/meadow-pals/words/nature-weather/star.png'],
  ['F','Flor','assets/meadow-pals/words/nature-weather/flower.png'],
  ['G','Gato','assets/meadow-pals/words/animals/cat.png'],
  ['H','Huevo','assets/meadow-pals/words/food-drink/egg.png'],
  ['I','Insecto','assets/meadow-pals/words/animals/bug.png'],
  ['J','Jugo','assets/meadow-pals/letters/j-juice.png'],
  ['K','Kiwi','assets/meadow-pals/letters-es/k-kiwi.png'],
  ['L','León','assets/meadow-pals/words/animals/lion.png'],
  ['M','Manzana','assets/meadow-pals/words/food-drink/apple.png'],
  ['N','Naranja','assets/meadow-pals/words/food-drink/orange.png'],
  ['Ñ','Niño','assets/meadow-pals/words/people/friend.png'],
  ['O','Oso','assets/meadow-pals/words/animals/bear.png'],
  ['P','Pato','assets/meadow-pals/words/animals/duck.png'],
  ['Q','Queso','assets/meadow-pals/words/food-drink/cheese.png'],
  ['R','Rana','assets/meadow-pals/words/animals/frog.png'],
  ['S','Sol','assets/meadow-pals/words/nature-weather/sun.png'],
  ['T','Tren','assets/meadow-pals/words/things-that-go/train.png'],
  ['U','Uno','assets/meadow-pals/numbers/1-apple.png'],
  ['V','Vaca','assets/meadow-pals/words/animals/cow.png'],
  ['W','Waffle','assets/meadow-pals/letters-es/w-waffle.png'],
  ['X','Xilófono','assets/meadow-pals/letters-es/x-xilofono.png'],
  ['Y','Yo-yo','assets/meadow-pals/letters-es/y-yoyo.png'],
  ['Z','Zapatos','assets/meadow-pals/words/clothing/shoes.png']
];

const SPANISH_LETTER_CHARACTERS = ['poppy','doodle','pip','poppy','pip','poppy','poppy','poppy','poppy','doodle','pip','pip','pip','poppy','poppy','pip','doodle','doodle','doodle','doodle','doodle','pip','pip','poppy','doodle','pip','poppy'];
const SPANISH_LETTER_CARDS = SPANISH_LETTER_EXAMPLES.map(([letter,example,image],index)=>({
  word:letter,image,character:SPANISH_LETTER_CHARACTERS[index],detail:`${letter} de ${example.toLowerCase()}`,speech:`${letter}. ${example}`,audio:''
}));

window.MEADOW_DATA = {
  numbers: NUMBER_CARDS,
  letters: LETTER_CARDS,
  lettersEs: SPANISH_LETTER_CARDS,
  colors: COLOR_CARDS,
  shapes: SHAPE_CARDS,
  colorsShapes: [...COLOR_CARDS,...SHAPE_CARDS],
  words: [
    ['Mommy','👩'],['Daddy','👨'],['Baby','👶'],['Family','👨‍👩‍👧'],['Friend','🧒'],['Dog','🐶'],['Cat','🐱'],['Bird','🐦'],['Fish','🐟'],['Duck','🦆'],
    ['Bear','🐻'],['Bunny','🐰'],['Cow','🐮'],['Pig','🐷'],['Horse','🐴'],['Lion','🦁'],['Monkey','🐵'],['Frog','🐸'],['Bug','🐞'],['Butterfly','🦋'],
    ['Ball','⚽'],['Book','📖'],['Car','🚗'],['Truck','🚚'],['Train','🚂'],['Boat','⛵'],['Plane','✈️'],['Bike','🚲'],['Doll','🪆'],['Blocks','🧱'],
    ['Cup','🥤'],['Spoon','🥄'],['Plate','🍽️'],['Chair','🪑'],['Bed','🛏️'],['Bath','🛁'],['Door','🚪'],['Light','💡'],['Clock','🕰️'],['Phone','📱'],
    ['Apple','🍎'],['Banana','🍌'],['Orange','🍊'],['Berry','🍓'],['Milk','🥛'],['Water','💧'],['Bread','🍞'],['Cheese','🧀'],['Egg','🥚'],['Cookie','🍪'],
    ['Head','🙂'],['Eyes','👀'],['Nose','👃'],['Mouth','👄'],['Ears','👂'],['Hands','🙌'],['Feet','🦶'],['Tummy','🧸'],['Hair','💇'],['Teeth','🦷'],
    ['Shirt','👕'],['Pants','👖'],['Shoes','👟'],['Socks','🧦'],['Hat','🧢'],['Coat','🧥'],['Dress','👗'],['Pajamas','🥱'],['Diaper','🧷'],['Boots','🥾'],
    ['Sun','☀️'],['Moon','🌙'],['Star','⭐'],['Cloud','☁️'],['Rain','🌧️'],['Snow','❄️'],['Tree','🌳'],['Flower','🌼'],['Grass','🌱'],['Sky','🌤️'],
    ['Hi','👋'],['Bye','👋'],['Yes','👍'],['No','🙅'],['Please','🙏'],['Thanks','💛'],['More','➕'],['All done','✅'],['Help','🤝'],['Love','❤️'],
    ['Happy','😊'],['Sad','😢'],['Mad','😠'],['Sleepy','😴'],['Hungry','😋'],['Big','🐘'],['Little','🐭'],['Hot','🔥'],['Cold','🧊'],['Gentle','🤲']
  ].map(([word,picture],index)=>{const asset=WORD_ASSETS[word]||{},character=asset.character||'',spanish=SPANISH_FIRST_WORDS[index];return {word,picture,image:asset.image||'',character,detail:word,speech:word,audio:character?`audio/voice-packs/${character}/words/${String(index+1).padStart(3,'0')}-${wordSlug(word)}.mp3`:'',spanish:{word:spanish,detail:spanish,speech:spanish,audio:character?`audio/voice-packs/${character}/words-es/${String(index+1).padStart(3,'0')}-${wordSlug(word)}.mp3`:''}}})
};

window.MEADOW_WORD_GROUPS = {
  people:{title:'People',spanishTitle:'Personas',icon:'👨‍👩‍👧',words:['Mommy','Daddy','Baby','Family','Friend']},
  animals:{title:'Animals',spanishTitle:'Animales',icon:'🐾',words:['Dog','Cat','Bird','Fish','Duck','Bear','Bunny','Cow','Pig','Horse','Lion','Monkey','Frog','Bug','Butterfly']},
  food:{title:'Food & Drink',spanishTitle:'Comida y bebida',icon:'🍎',words:['Apple','Banana','Orange','Berry','Milk','Water','Bread','Cheese','Egg','Cookie']},
  things:{title:'Things That Go',spanishTitle:'Transportes',icon:'🚗',words:['Car','Truck','Train','Boat','Plane']},
  play:{title:'Toys & Play',spanishTitle:'Juegos y juguetes',icon:'🧸',words:['Ball','Book','Bike','Doll','Blocks']},
  home:{title:'Home & Everyday',spanishTitle:'La casa',icon:'🏠',words:['Cup','Spoon','Plate','Chair','Bed','Bath','Door','Light','Clock','Phone']},
  body:{title:'Body Parts',spanishTitle:'Partes del cuerpo',icon:'🙌',words:['Head','Eyes','Nose','Mouth','Ears','Hands','Feet','Tummy','Hair','Teeth']},
  clothing:{title:'Clothing',spanishTitle:'Ropa',icon:'👕',words:['Shirt','Pants','Shoes','Socks','Hat','Coat','Dress','Pajamas','Diaper','Boots']},
  nature:{title:'Nature & Weather',spanishTitle:'Naturaleza y clima',icon:'🌦️',words:['Sun','Moon','Star','Cloud','Rain','Snow','Tree','Flower','Grass','Sky']},
  social:{title:'Useful Social Words',spanishTitle:'Palabras sociales',icon:'👋',words:['Hi','Bye','Yes','No','Please','Thanks','More','All done','Help','Love']},
  feelings:{title:'Feelings & Describing',spanishTitle:'Sentimientos',icon:'😊',words:['Happy','Sad','Mad','Sleepy','Hungry','Big','Little','Hot','Cold','Gentle']}
};
