const NUMBER_CARDS = [
  {word:'0',speech:'Zero',image:'assets/meadow-pals/numbers/0-empty-basket.png',audio:'audio/voice-packs/pip/numbers/001-0.mp3',detail:'An empty basket means zero.'},
  {word:'1',speech:'One',image:'assets/meadow-pals/numbers/1-apple.png',audio:'audio/voice-packs/pip/numbers/002-1.mp3',detail:'Pip is holding one apple.'},
  {word:'2',speech:'Two',image:'assets/meadow-pals/numbers/2-birds.png',audio:'audio/voice-packs/poppy/numbers/003-2.mp3',detail:'Poppy found two birds.'},
  {word:'3',speech:'Three',image:'assets/meadow-pals/numbers/3-ducklings.png',audio:'audio/voice-packs/doodle/numbers/004-3.mp3',detail:'Three ducklings are together.'},
  {word:'4',speech:'Four',image:'assets/meadow-pals/numbers/4-blocks.png',audio:'audio/voice-packs/pip/numbers/005-4.mp3',detail:'Pip has four blocks.'},
  {word:'5',speech:'Five',image:'assets/meadow-pals/numbers/5-flowers.png',audio:'audio/voice-packs/poppy/numbers/006-5.mp3',detail:'Poppy sees five flowers.'},
  {word:'6',speech:'Six',image:'assets/meadow-pals/numbers/6-bubbles.png',audio:'audio/voice-packs/doodle/numbers/007-6.mp3',detail:'Doodle counts six bubbles.'},
  {word:'7',speech:'Seven',image:'assets/meadow-pals/numbers/7-strawberries.png',audio:'audio/voice-packs/pip/numbers/008-7.mp3',detail:'Pip found seven strawberries.'},
  {word:'8',speech:'Eight',image:'assets/meadow-pals/numbers/8-balloons.png',audio:'audio/voice-packs/poppy/numbers/009-8.mp3',detail:'Poppy has eight balloons.'},
  {word:'9',speech:'Nine',image:'assets/meadow-pals/numbers/9-balls.png',audio:'audio/voice-packs/doodle/numbers/010-9.mp3',detail:'Doodle counts nine balls.'},
  {word:'10',speech:'Ten',image:'assets/meadow-pals/numbers/10-stars.png',audio:'audio/voice-packs/pip/numbers/011-10.mp3',detail:'The pals found ten stars!'}
];

const WORD_ASSETS = {
  Head:{image:'assets/meadow-pals/words/body-parts/head.png',character:'pip'},
  Eyes:{image:'assets/meadow-pals/words/body-parts/eyes.png',character:'poppy'},
  Nose:{image:'assets/meadow-pals/words/body-parts/nose.png',character:'pip'},
  Mouth:{image:'assets/meadow-pals/words/body-parts/mouth.png',character:'pip'},
  Ears:{image:'assets/meadow-pals/words/body-parts/ears.png',character:'poppy'},
  Hands:{image:'assets/meadow-pals/words/body-parts/hands.png',character:'poppy'},
  Feet:{image:'assets/meadow-pals/words/body-parts/feet.png',character:'doodle'},
  Tummy:{image:'assets/meadow-pals/words/body-parts/tummy.png',character:'doodle'},
  Hair:{image:'assets/meadow-pals/words/body-parts/hair.png',character:'pip'},
  Teeth:{image:'assets/meadow-pals/words/body-parts/teeth.png',character:'poppy'},
  Dog:{image:'assets/meadow-pals/words/animals/dog.png',character:'pip'},
  Cat:{image:'assets/meadow-pals/words/animals/cat.png',character:'poppy'},
  Bird:{image:'assets/meadow-pals/words/animals/bird.png',character:'poppy'},
  Fish:{image:'assets/meadow-pals/words/animals/fish.png',character:'doodle'},
  Duck:{image:'assets/meadow-pals/words/animals/duck.png',character:'doodle'},
  Bear:{image:'assets/meadow-pals/words/animals/bear.png',character:'pip'},
  Bunny:{image:'assets/meadow-pals/words/animals/bunny.png',character:'poppy'},
  Cow:{image:'assets/meadow-pals/words/animals/cow.png',character:'pip'},
  Pig:{image:'assets/meadow-pals/words/animals/pig.png',character:'poppy'},
  Horse:{image:'assets/meadow-pals/words/animals/horse.png',character:'pip'},
  Lion:{image:'assets/meadow-pals/words/animals/lion.png',character:'pip'},
  Monkey:{image:'assets/meadow-pals/words/animals/monkey.png',character:'doodle'},
  Frog:{image:'assets/meadow-pals/words/animals/frog.png',character:'doodle'},
  Bug:{image:'assets/meadow-pals/words/animals/bug.png',character:'poppy'},
  Butterfly:{image:'assets/meadow-pals/words/animals/butterfly.png',character:'poppy'},
  Apple:{image:'assets/meadow-pals/words/food-drink/apple.png',character:'pip'},
  Banana:{image:'assets/meadow-pals/words/food-drink/banana.png',character:'doodle'},
  Orange:{image:'assets/meadow-pals/words/food-drink/orange.png',character:'poppy'},
  Berry:{image:'assets/meadow-pals/words/food-drink/berry.png',character:'pip'},
  Milk:{image:'assets/meadow-pals/words/food-drink/milk.png',character:'doodle'},
  Water:{image:'assets/meadow-pals/words/food-drink/water.png',character:'poppy'},
  Bread:{image:'assets/meadow-pals/words/food-drink/bread.png',character:'pip'},
  Cheese:{image:'assets/meadow-pals/words/food-drink/cheese.png',character:'doodle'},
  Egg:{image:'assets/meadow-pals/words/food-drink/egg.png',character:'poppy'},
  Cookie:{image:'assets/meadow-pals/words/food-drink/cookie.png',character:'doodle'},
  Happy:{image:'assets/meadow-pals/words/feelings-describing/happy.png',character:'doodle'},
  Sad:{image:'assets/meadow-pals/words/feelings-describing/sad.png',character:'poppy'},
  Mad:{image:'assets/meadow-pals/words/feelings-describing/mad.png',character:'pip'},
  Sleepy:{image:'assets/meadow-pals/words/feelings-describing/sleepy.png',character:'doodle'},
  Hungry:{image:'assets/meadow-pals/words/feelings-describing/hungry.png',character:'pip'},
  Big:{image:'assets/meadow-pals/words/feelings-describing/big.png',character:'pip'},
  Little:{image:'assets/meadow-pals/words/feelings-describing/little.png',character:'doodle'},
  Hot:{image:'assets/meadow-pals/words/feelings-describing/hot.png',character:'poppy'},
  Cold:{image:'assets/meadow-pals/words/feelings-describing/cold.png',character:'pip'},
  Gentle:{image:'assets/meadow-pals/words/feelings-describing/gentle.png',character:'poppy'}
};

window.MEADOW_DATA = {
  numbers: NUMBER_CARDS,
  letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((letter,index)=>({word:letter,picture:['🍎','🐻','🐱','🐶','🥚','🐸','🍇','🏠','🍦','🧃','🔑','🍃','🌙','🌙','🍊','🐷','👑','🌈','☀️','🐯','☂️','🎻','🐳','📦','🪀','🦓'][index],detail:`${letter} is for ${['apple','bear','cat','dog','egg','frog','grapes','house','ice cream','juice','key','leaf','moon','night','orange','pig','queen','rainbow','sun','tiger','umbrella','violin','whale','box','yo-yo','zebra'][index]}`,speech:`${letter}. ${['apple','bear','cat','dog','egg','frog','grapes','house','ice cream','juice','key','leaf','moon','night','orange','pig','queen','rainbow','sun','tiger','umbrella','violin','whale','box','yo-yo','zebra'][index]}`,audio:`audio/voice-packs/poppy/letters/${String(index+1).padStart(3,'0')}-${letter.toLowerCase()}.mp3`})),
  colors: [['Red','#ef5d5d','🍓'],['Orange','#f59c45','🍊'],['Yellow','#f6cf4a','☀️'],['Pink','#f49abb','🌸'],['Purple','#9b79d1','🍇'],['Green','#70b978','🌿'],['Blue','#5b9bd5','🐳'],['Black','#343643','🐈‍⬛'],['Brown','#95664b','🐻']].map(([word,color,picture],index)=>({word,picture,detail:`${word} is a wonderful color`,color,speech:word,audio:`audio/voice-packs/doodle/colors/${String(index+1).padStart(3,'0')}-${word.toLowerCase()}.mp3`})),
  words: [
    ['Mommy','👩'],['Daddy','👨'],['Baby','👶'],['Family','👨‍👩‍👧'],['Friend','🧒'],['Dog','🐶'],['Cat','🐱'],['Bird','🐦'],['Fish','🐟'],['Duck','🦆'],
    ['Bear','🐻'],['Bunny','🐰'],['Cow','🐮'],['Pig','🐷'],['Horse','🐴'],['Lion','🦁'],['Monkey','🐵'],['Frog','🐸'],['Bug','🐞'],['Butterfly','🦋'],
    ['Ball','⚽'],['Book','📖'],['Car','🚗'],['Truck','🚚'],['Train','🚂'],['Boat','⛵'],['Plane','✈️'],['Bike','🚲'],['Doll','🪆'],['Blocks','🧱'],
    ['Cup','🥤'],['Spoon','🥄'],['Plate','🍽️'],['Chair','🪑'],['Bed','🛏️'],['Bath','🛁'],['Door','🚪'],['Light','💡'],['Clock','🕰️'],['Phone','📱'],
    ['Apple','🍎'],['Banana','🍌'],['Orange','🍊'],['Berry','🍓'],['Milk','🥛'],['Water','💧'],['Bread','🍞'],['Cheese','🧀'],['Egg','🥚'],['Cookie','🍪'],
    ['Head','🙂'],['Eyes','👀'],['Nose','👃'],['Mouth','👄'],['Ears','👂'],['Hands','🙌'],['Feet','🦶'],['Tummy','🧸'],['Hair','💇'],['Teeth','🦷'],
    ['Shirt','👕'],['Pants','👖'],['Shoes','👟'],['Socks','🧦'],['Hat','🧢'],['Coat','🧥'],['Dress','👗'],['Pajamas','🥱'],['Diaper','🧷'],['Boots','🥾'],
    ['Sun','☀️'],['Moon','🌙'],['Star','⭐'],['Cloud','☁️'],['Rain','🌧️'],['Snow','❄️'],['Tree','🌳'],['Flower','🌼'],['Grass','🌱'],['Sky','🌤️'],
    ['Hi','👋'],['Bye','👋'],['Yes','👍'],['No','🙅'],['Please','🙏'],['Thanks','💛'],['More','➕'],['All done','✅'],['Help','🤝'],['Love','❤️'],
    ['Happy','😊'],['Sad','😢'],['Mad','😠'],['Sleepy','😴'],['Hungry','😋'],['Big','🐘'],['Little','🐭'],['Hot','🔥'],['Cold','🧊'],['Gentle','🤲']
  ].map(([word,picture])=>{const asset=WORD_ASSETS[word]||{};return {word,picture,image:asset.image||'',character:asset.character||'',detail:word,speech:word}})
};

window.MEADOW_WORD_GROUPS = {
  people:{title:'People',icon:'👨‍👩‍👧',words:['Mommy','Daddy','Baby','Family','Friend']},
  animals:{title:'Animals',icon:'🐾',words:['Dog','Cat','Bird','Fish','Duck','Bear','Bunny','Cow','Pig','Horse','Lion','Monkey','Frog','Bug','Butterfly']},
  food:{title:'Food & Drink',icon:'🍎',words:['Apple','Banana','Orange','Berry','Milk','Water','Bread','Cheese','Egg','Cookie']},
  things:{title:'Things That Go',icon:'🚗',words:['Car','Truck','Train','Boat','Plane']},
  play:{title:'Toys & Play',icon:'🧸',words:['Ball','Book','Bike','Doll','Blocks']},
  home:{title:'Home & Everyday',icon:'🏠',words:['Cup','Spoon','Plate','Chair','Bed','Bath','Door','Light','Clock','Phone']},
  body:{title:'Body Parts',icon:'🙌',words:['Head','Eyes','Nose','Mouth','Ears','Hands','Feet','Tummy','Hair','Teeth']},
  clothing:{title:'Clothing',icon:'👕',words:['Shirt','Pants','Shoes','Socks','Hat','Coat','Dress','Pajamas','Diaper','Boots']},
  nature:{title:'Nature & Weather',icon:'🌦️',words:['Sun','Moon','Star','Cloud','Rain','Snow','Tree','Flower','Grass','Sky']},
  social:{title:'Useful Social Words',icon:'👋',words:['Hi','Bye','Yes','No','Please','Thanks','More','All done','Help','Love']},
  feelings:{title:'Feelings & Describing',icon:'😊',words:['Happy','Sad','Mad','Sleepy','Hungry','Big','Little','Hot','Cold','Gentle']}
};
