const NUMBER_CARDS = [
  {word:'0',speech:'Zero',image:'assets/meadow-pals/numbers/0-empty-basket.png',audio:'audio/voice-packs/pip/numbers/001-0.mp3',detail:'An empty basket means zero.'},
  {word:'1',speech:'One',image:'assets/meadow-pals/numbers/1-apple.png',audio:'audio/voice-packs/pip/numbers/002-1.mp3',detail:'Pip is holding one apple.'},
  {word:'2',speech:'Two',image:'assets/meadow-pals/numbers/2-birds.png',audio:'audio/voice-packs/poppy/numbers/003-2.mp3',detail:'Poppy found two birds.'},
  {word:'3',speech:'Three',image:'assets/meadow-pals/numbers/3-ducklings.png',audio:'audio/voice-packs/doodle/numbers/004-3.mp3',detail:'Three ducklings are together.'},
  {word:'4',speech:'Four',image:'assets/meadow-pals/numbers/4-blocks.png',audio:'audio/voice-packs/pip/numbers/005-4.mp3',detail:'Pip has four blocks.'},
  {word:'5',speech:'Five',image:'assets/meadow-pals/numbers/5-flowers.png',audio:'audio/voice-packs/poppy/numbers/006-5.mp3',detail:'Poppy sees five flowers.'},
  {word:'6',speech:'Six',image:'assets/meadow-pals/numbers/6-bubbles.png',audio:'audio/voice-packs/doodle/numbers/007-6.mp3',detail:'Doodle counts six bubbles.'},
  {word:'7',speech:'Seven',image:'assets/meadow-pals/numbers/7-strawberries.png',audio:'audio/voice-packs/pip/numbers/008-7.mp3',detail:'Pip found seven strawberries.'},
  {word:'8',speech:'Eight',image:'assets/meadow-pals/numbers/8-balloons.png',audio:'audio/voice-packs/poppy/numbers/009-8.mp3',detail:'Poppy has eight balloons.'},
  {word:'9',speech:'Nine',image:'assets/meadow-pals/numbers/9-balls.png',audio:'audio/voice-packs/doodle/numbers/010-9.mp3',detail:'Doodle counts nine balls.'},
  {word:'10',speech:'Ten',image:'assets/meadow-pals/numbers/10-stars.png',audio:'audio/voice-packs/pip/numbers/011-10.mp3',detail:'The pals found ten stars!'}
];

const WORD_ASSETS = {
  Head:{image:'assets/meadow-pals/words/body-parts/head.png',character:'pip'},
  Eyes:{image:'assets/meadow-pals/words/body-parts/eyes.png',character:'poppy'},
  Nose:{image:'assets/meadow-pals/words/body-parts/nose.png',character:'pip'},
  Mouth:{image:'assets/meadow-pals/words/body-parts/mouth.png',character:'pip'},
  Ears:{image:'assets/meadow-pals/words/body-parts/ears.png',character:'poppy'},
  Hands:{image:'assets/meadow-pals/words/body-parts/hands.png',character:'poppy'},
  Feet:{image:'assets/meadow-pals/words/body-parts/feet.png',character:'doodle'},
  Tummy:{image:'assets/meadow-pals/words/body-parts/tummy.png',character:'doodle'},
  Hair:{image:'assets/meadow-pals/words/body-parts/hair.png',character:'pip'},
  Teeth:{image:'assets/meadow-pals/words/body-parts/teeth.png',character:'poppy'},
  Dog:{image:'assets/meadow-pals/words/animals/dog.png',character:'pip'},
  Cat:{image:'assets/meadow-pals/words/animals/cat.png',character:'poppy'},
  Bird:{image:'assets/meadow-pals/words/animals/bird.png',character:'poppy'},
  Fish:{image:'assets/meadow-pals/words/animals/fish.png',character:'doodle'},
  Duck:{image:'assets/meadow-pals/words/animals/duck.png',character:'doodle'},
  Bear:{image:'assets/meadow-pals/words/animals/bear.png',character:'pip'},
  Bunny:{image:'assets/meadow-pals/words/animals/bunny.png',character:'poppy'},
  Cow:{image:'assets/meadow-pals/words/animals/cow.png',character:'pip'},
  Pig:{image:'assets/meadow-pals/words/animals/pig.png',character:'poppy'},
  Horse:{image:'assets/meadow-pals/words/animals/horse.png',character:'pip'},
  Lion:{image:'assets/meadow-pals/words/animals/lion.png',character:'pip'},
  Monkey:{image:'assets/meadow-pals/words/animals/monkey.png',character:'doodle'},
  Frog:{image:'assets/meadow-pals/words/animals/frog.png',character:'doodle'},
  Bug:{image:'assets/meadow-pals/words/animals/bug.png',character:'poppy'},
  Butterfly:{image:'assets/meadow-pals/words/animals/butterfly.png',character:'poppy'},
  Apple:{image:'assets/meadow-pals/words/food-drink/apple.png',character:'pip'},
  Banana:{image:'assets/meadow-pals/words/food-drink/banana.png',character:'doodle'},
  Orange:{image:'assets/meadow-pals/words/food-drink/orange.png',character:'poppy'},
  Berry:{image:'assets/meadow-pals/words/food-drink/berry.png',character:'pip'},
  Milk:{image:'assets/meadow-pals/words/food-drink/milk.png',character:'doodle'},
  Water:{image:'assets/meadow-pals/words/food-drink/water.png',character:'poppy'},
  Bread:{image:'assets/meadow-pals/words/food-drink/bread.png',character:'pip'},
  Cheese:{image:'assets/meadow-pals/words/food-drink/cheese.png',character:'doodle'},
  Egg:{image:'assets/meadow-pals/words/food-drink/egg.png',character:'poppy'},
  Cookie:{image:'assets/meadow-pals/words/food-drink/cookie.png',character:'doodle'},
  Happy:{image:'assets/meadow-pals/words/feelings-describing/happy.png',character:'doodle'},
  Sad:{image:'assets/meadow-pals/words/feelings-describing/sad.png',character:'poppy'},
  Mad:{image:'assets/meadow-pals/words/feelings-describing/mad.png',character:'pip'},
  Sleepy:{image:'assets/meadow-pals/words/feelings-describing/sleepy.png',character:'doodle'},
  Hungry:{image:'assets/meadow-pals/words/feelings-describing/hungry.png',character:'pip'},
  Big:{image:'assets/meadow-pals/words/feelings-describing/big.png',character:'pip'},
  Little:{image:'assets/meadow-pals/words/feelings-describing/little.png',character:'doodle'},
  Hot:{image:'assets/meadow-pals/words/feelings-describing/hot.png',character:'poppy'},
  Cold:{image:'assets/meadow-pals/words/feelings-describing/cold.png',character:'pip'},
  Gentle:{image:'assets/meadow-pals/words/feelings-describing/gentle.png',character:'poppy'},
  Mommy:{image:'assets/meadow-pals/words/people/mommy.png',character:'poppy'},
  Daddy:{image:'assets/meadow-pals/words/people/daddy.png',character:'pip'},
  Baby:{image:'assets/meadow-pals/words/people/baby.png',character:'doodle'},
  Family:{image:'assets/meadow-pals/words/people/family.png',character:'pip'},
  Friend:{image:'assets/meadow-pals/words/people/friend.png',character:'poppy'},
  Car:{image:'assets/meadow-pals/words/things-that-go/car.png',character:'pip'},
  Truck:{image:'assets/meadow-pals/words/things-that-go/truck.png',character:'poppy'},
  Train:{image:'assets/meadow-pals/words/things-that-go/train.png',character:'doodle'},
  Boat:{image:'assets/meadow-pals/words/things-that-go/boat.png',character:'poppy'},
  Plane:{image:'assets/meadow-pals/words/things-that-go/plane.png',character:'pip'},
  Ball:{image:'assets/meadow-pals/words/toys-play/ball.png',character:'doodle'},
  Book:{image:'assets/meadow-pals/words/toys-play/book.png',character:'poppy'},
  Bike:{image:'assets/meadow-pals/words/toys-play/bike.png',character:'pip'},
  Doll:{image:'assets/meadow-pals/words/toys-play/doll.png',character:'poppy'},
  Blocks:{image:'assets/meadow-pals/words/toys-play/blocks.png',character:'doodle'},
  Sun:{image:'assets/meadow-pals/words/nature-weather/sun.png',character:'doodle'},
  Moon:{image:'assets/meadow-pals/words/nature-weather/moon.png',character:'poppy'},
  Star:{image:'assets/meadow-pals/words/nature-weather/star.png',character:'pip'},
  Cloud:{image:'assets/meadow-pals/words/nature-weather/cloud.png',character:'doodle'},
  Rain:{image:'assets/meadow-pals/words/nature-weather/rain.png',character:'poppy'},
  Snow:{image:'assets/meadow-pals/words/nature-weather/snow.png',character:'pip'},
  Tree:{image:'assets/meadow-pals/words/nature-weather/tree.png',character:'pip'},
  Flower:{image:'assets/meadow-pals/words/nature-weather/flower.png',character:'poppy'},
  Grass:{image:'assets/meadow-pals/words/nature-weather/grass.png',character:'doodle'},
  Sky:{image:'assets/meadow-pals/words/nature-weather/sky.png',character:'poppy'},
  Hi:{image:'assets/meadow-pals/words/useful-social/hi.png',character:'poppy'},
  Bye:{image:'assets/meadow-pals/words/useful-social/bye.png',character:'doodle'},
  Yes:{image:'assets/meadow-pals/words/useful-social/yes.png',character:'pip'},
  No:{image:'assets/meadow-pals/words/useful-social/no.png',character:'poppy'},
  Please:{image:'assets/meadow-pals/words/useful-social/please.png',character:'doodle'},
  Thanks:{image:'assets/meadow-pals/words/useful-social/thanks.png',character:'poppy'},
  More:{image:'assets/meadow-pals/words/useful-social/more.png',character:'pip'},
  'All done':{image:'assets/meadow-pals/words/useful-social/all-done.png',character:'doodle'},
  Help:{image:'assets/meadow-pals/words/useful-social/help.png',character:'pip'},
  Love:{image:'assets/meadow-pals/words/useful-social/love.png',character:'poppy'},
  Cup:{image:'assets/meadow-pals/words/home-everyday/cup.png',character:'pip'},
  Spoon:{image:'assets/meadow-pals/words/home-everyday/spoon.png',character:'doodle'},
  Plate:{image:'assets/meadow-pals/words/home-everyday/plate.png',character:'poppy'},
  Chair:{image:'assets/meadow-pals/words/home-everyday/chair.png',character:'pip'},
  Bed:{image:'assets/meadow-pals/words/home-everyday/bed.png',character:'doodle'},
  Bath:{image:'assets/meadow-pals/words/home-everyday/bath.png',character:'poppy'},
  Door:{image:'assets/meadow-pals/words/home-everyday/door.png',character:'pip'},
  Light:{image:'assets/meadow-pals/words/home-everyday/light.png',character:'doodle'},
  Clock:{image:'assets/meadow-pals/words/home-everyday/clock.png',character:'poppy'},
  Phone:{image:'assets/meadow-pals/words/home-everyday/phone.png',character:'pip'},
  Shirt:{image:'assets/meadow-pals/words/clothing/shirt.png',character:'pip'},
  Pants:{image:'assets/meadow-pals/words/clothing/pants.png',character:'doodle'},
  Shoes:{image:'assets/meadow-pals/words/clothing/shoes.png',character:'poppy'},
  Socks:{image:'assets/meadow-pals/words/clothing/socks.png',character:'doodle'},
  Hat:{image:'assets/meadow-pals/words/clothing/hat.png',character:'pip'},
  Coat:{image:'assets/meadow-pals/words/clothing/coat.png',character:'poppy'},
  Dress:{image:'assets/meadow-pals/words/clothing/dress.png',character:'poppy'},
  Pajamas:{character:'doodle'},
  Diaper:{character:'doodle'},
  Boots:{character:'pip'}
};

const wordSlug=value=>value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'card';

const SPANISH_FIRST_WORDS = [
  'Mamá','Papá','Bebé','Familia','Amigo','Perro','Gato','Pájaro','Pez','Pato',
  'Oso','Conejo','Vaca','Cerdo','Caballo','León','Mono','Rana','Insecto','Mariposa',
  'Pelota','Libro','Carro','Camión','Tren','Barco','Avión','Bicicleta','Muñeca','Bloques',
  'Vaso','Cuchara','Plato','Silla','Cama','Baño','Puerta','Luz','Reloj','Teléfono',
  'Manzana','Banana','Naranja','Fresa','Leche','Agua','Pan','Queso','Huevo','Galleta',
  'Cabeza','Ojos','Nariz','Boca','Orejas','Manos','Pies','Barriga','Pelo','Dientes',
  'Camisa','Pantalones','Zapatos','Calcetines','Sombrero','Abrigo','Vestido','Pijama','Pañal','Botas',
  'Sol','Luna','Estrella','Nube','Lluvia','Nieve','Árbol','Flor','Pasto','Cielo',
  'Hola','Adiós','Sí','No','Por favor','Gracias','Más','Se acabó','Ayuda','Amor',
  'Feliz','Triste','Enojado','Con sueño','Con hambre','Grande','Pequeño','Caliente','Frío','Suave'
];

window.MEADOW_DATA = {
  numbers: NUMBER_CARDS,
  letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((letter,index)=>({word:letter,picture:['🍎','🐻','🐱','🐶','🥚','🐸','🍇','🏠','🍦','🧃','🔑','🍃','🌙','🌙','🍊','🐷','👑','🌈','☀️','🐯','☂️','🎻','🐳','📦','🪀','🦓'][index],detail:`${letter} is for ${['apple','bear','cat','dog','egg','frog','grapes','house','ice cream','juice','key','leaf','moon','night','orange','pig','queen','rainbow','sun','tiger','umbrella','violin','whale','box','yo-yo','zebra'][index]}`,speech:`${letter}. ${['apple','bear','cat','dog','egg','frog','grapes','house','ice cream','juice','key','leaf','moon','night','orange','pig','queen','rainbow','sun','tiger','umbrella','violin','whale','box','yo-yo','zebra'][index]}`,audio:`audio/voice-packs/poppy/letters/${String(index+1).padStart(3,'0')}-${letter.toLowerCase()}.mp3`})),
  colors: [['Red','#ef5d5d','🍓'],['Orange','#f59c45','🍊'],['Yellow','#f6cf4a','☀️'],['Pink','#f49abb','🌸'],['Purple','#9b79d1','🍇'],['Green','#70b978','🌿'],['Blue','#5b9bd5','🐳'],['Black','#343643','🐈‍⬛'],['Brown','#95664b','🐻']].map(([word,color,picture],index)=>({word,picture,detail:`${word} is a wonderful color`,color,speech:word,audio:`audio/voice-packs/doodle/colors/${String(index+1).padStart(3,'0')}-${word.toLowerCase()}.mp3`})),
  words: [
    ['Mommy','👩'],['Daddy','👨'],['Baby','👶'],['Family','👨‍👩‍👧'],['Friend','🧒'],['Dog','🐶'],['Cat','🐱'],['Bird','🐦'],['Fish','🐟'],['Duck','🦆'],
    ['Bear','🐻'],['Bunny','🐰'],['Cow','🐮'],['Pig','🐷'],['Horse','🐴'],['Lion','🦁'],['Monkey','🐵'],['Frog','🐸'],['Bug','🐞'],['Butterfly','🦋'],
    ['Ball','⚽'],['Book','📖'],['Car','🚗'],['Truck','🚚'],['Train','🚂'],['Boat','⛵'],['Plane','✈️'],['Bike','🚲'],['Doll','🪆'],['Blocks','🧱'],
    ['Cup','🥤'],['Spoon','🥄'],['Plate','🍽️'],['Chair','🪑'],['Bed','🛏️'],['Bath','🛁'],['Door','🚪'],['Light','💡'],['Clock','🕰️'],['Phone','📱'],
    ['Apple','🍎'],['Banana','🍌'],['Orange','🍊'],['Berry','🍓'],['Milk','🥛'],['Water','💧'],['Bread','🍞'],['Cheese','🧀'],['Egg','🥚'],['Cookie','🍪'],
    ['Head','🙂'],['Eyes','👀'],['Nose','👃'],['Mouth','👄'],['Ears','👂'],['Hands','🙌'],['Feet','🦶'],['Tummy','🧸'],['Hair','💇'],['Teeth','🦷'],
    ['Shirt','👕'],['Pants','👖'],['Shoes','👟'],['Socks','🧦'],['Hat','🧢'],['Coat','🧥'],['Dress','👗'],['Pajamas','🥱'],['Diaper','🧷'],['Boots','🥾'],
    ['Sun','☀️'],['Moon','🌙'],['Star','⭐'],['Cloud','☁️'],['Rain','🌧️'],['Snow','❄️'],['Tree','🌳'],['Flower','🌼'],['Grass','🌱'],['Sky','🌤️'],
    ['Hi','👋'],['Bye','👋'],['Yes','👍'],['No','🙅'],['Please','🙏'],['Thanks','💛'],['More','➕'],['All done','✅'],['Help','🤝'],['Love','❤️'],
    ['Happy','😊'],['Sad','😢'],['Mad','😠'],['Sleepy','😴'],['Hungry','😋'],['Big','🐘'],['Little','🐭'],['Hot','🔥'],['Cold','🧊'],['Gentle','🤲']
  ].map(([word,picture],index)=>{const asset=WORD_ASSETS[word]||{},character=asset.character||'',spanish=SPANISH_FIRST_WORDS[index];return {word,picture,image:asset.image||'',character,detail:word,speech:word,audio:character?`audio/voice-packs/${character}/words/${String(index+1).padStart(3,'0')}-${wordSlug(word)}.mp3`:'',spanish:{word:spanish,detail:spanish,speech:spanish,audio:character?`audio/voice-packs/${character}/words-es/${String(index+1).padStart(3,'0')}-${wordSlug(word)}.mp3`:''}}})
};

window.MEADOW_WORD_GROUPS = {
  people:{title:'People',spanishTitle:'Personas',icon:'👨‍👩‍👧',words:['Mommy','Daddy','Baby','Family','Friend']},
  animals:{title:'Animals',spanishTitle:'Animales',icon:'🐾',words:['Dog','Cat','Bird','Fish','Duck','Bear','Bunny','Cow','Pig','Horse','Lion','Monkey','Frog','Bug','Butterfly']},
  food:{title:'Food & Drink',spanishTitle:'Comida y bebida',icon:'🍎',words:['Apple','Banana','Orange','Berry','Milk','Water','Bread','Cheese','Egg','Cookie']},
  things:{title:'Things That Go',spanishTitle:'Transportes',icon:'🚗',words:['Car','Truck','Train','Boat','Plane']},
  play:{title:'Toys & Play',spanishTitle:'Juegos y juguetes',icon:'🧸',words:['Ball','Book','Bike','Doll','Blocks']},
  home:{title:'Home & Everyday',spanishTitle:'La casa',icon:'🏠',words:['Cup','Spoon','Plate','Chair','Bed','Bath','Door','Light','Clock','Phone']},
  body:{title:'Body Parts',spanishTitle:'Partes del cuerpo',icon:'🙌',words:['Head','Eyes','Nose','Mouth','Ears','Hands','Feet','Tummy','Hair','Teeth']},
  clothing:{title:'Clothing',spanishTitle:'Ropa',icon:'👕',words:['Shirt','Pants','Shoes','Socks','Hat','Coat','Dress','Pajamas','Diaper','Boots']},
  nature:{title:'Nature & Weather',spanishTitle:'Naturaleza y clima',icon:'🌦️',words:['Sun','Moon','Star','Cloud','Rain','Snow','Tree','Flower','Grass','Sky']},
  social:{title:'Useful Social Words',spanishTitle:'Palabras sociales',icon:'👋',words:['Hi','Bye','Yes','No','Please','Thanks','More','All done','Help','Love']},
  feelings:{title:'Feelings & Describing',spanishTitle:'Sentimientos',icon:'😊',words:['Happy','Sad','Mad','Sleepy','Hungry','Big','Little','Hot','Cold','Gentle']}
};
