const CACHE='meadow-pals-v58';
const REFRESHED_LETTERS=new Set(['g','h','l','n','r','t','w','y']);
const LETTER_AUDIO=Array.from({length:26},(_,index)=>{const letter=String.fromCharCode(97+index);return `./audio/voice-packs/poppy/letters/${String(index+1).padStart(3,'0')}-${letter}${REFRESHED_LETTERS.has(letter)?'-refresh':''}.mp3`});
const COLOR_AUDIO=['red','orange','yellow','pink','purple','green','blue','black','brown'].map((color,index)=>`./audio/voice-packs/doodle/colors/${String(index+1).padStart(3,'0')}-${color}.mp3`);
const SHAPE_AUDIO={doodle:['001-circle','004-rectangle','007-star'],pip:['002-square','005-oval','008-heart'],poppy:['003-triangle','006-diamond','009-crescent']};
const SHAPE_AUDIO_FILES=Object.entries(SHAPE_AUDIO).flatMap(([voice,names])=>names.map(name=>`./audio/voice-packs/${voice}/shapes/${name}.mp3`));
const LETTER_ART=['i-ice-cream','j-juice','k-key','q-queen','v-violin','x-box','z-zebra'].map(name=>`./assets/meadow-pals/letters/${name}.png`);
const COLOR_ART=['red','orange','yellow','pink','purple','green','blue','black','brown'].map(name=>`./assets/meadow-pals/colors/${name}.png`);
const SHAPE_ART=['circle','square','triangle','rectangle','oval','diamond','star','heart','crescent'].map(name=>`./assets/meadow-pals/shapes/${name}.png`);
const SPANISH_LETTER_ART=['k-kiwi','w-waffle','x-xilofono','y-yoyo'].map(name=>`./assets/meadow-pals/letters-es/${name}.png`);
const BODY_PART_ART=['head','eyes','nose','mouth','ears','hands','feet','tummy','hair','teeth'].map(name=>`./assets/meadow-pals/words/body-parts/${name}.png`);
const ANIMAL_ART=['dog','cat','bird','fish','duck','bear','bunny','cow','pig','horse','lion','monkey','frog','bug','butterfly'].map(name=>`./assets/meadow-pals/words/animals/${name}.png`);
const FOOD_ART=['apple','banana','orange','berry','milk','water','bread','cheese','egg','cookie'].map(name=>`./assets/meadow-pals/words/food-drink/${name}.png`);
const FEELINGS_ART=['happy','sad','mad','sleepy','hungry','big','little','hot','cold','gentle'].map(name=>`./assets/meadow-pals/words/feelings-describing/${name}.png`);
const PEOPLE_ART=['mommy','daddy','baby','family','friend'].map(name=>`./assets/meadow-pals/words/people/${name}.png`);
const THINGS_ART=['car','truck','train','boat','plane'].map(name=>`./assets/meadow-pals/words/things-that-go/${name}.png`);
const PLAY_ART=['ball','book','bike','doll','blocks'].map(name=>`./assets/meadow-pals/words/toys-play/${name}.png`);
const NATURE_ART=['sun','moon','star','cloud','rain','snow','tree','flower','grass','sky'].map(name=>`./assets/meadow-pals/words/nature-weather/${name}.png`);
const SOCIAL_ART=['hi','bye','yes','no','please','thanks','more','all-done','help','love'].map(name=>`./assets/meadow-pals/words/useful-social/${name}.png`);
const HOME_ART=['cup','spoon','plate','chair','bed','bath','door','light','clock','phone'].map(name=>`./assets/meadow-pals/words/home-everyday/${name}.png`);
const CLOTHING_ART=['shirt','pants','shoes','socks','hat','coat','dress','pajamas','diaper','boots'].map(name=>`./assets/meadow-pals/words/clothing/${name}.png`);
const WORD_AUDIO_GROUPS={
  pip:['002-daddy','004-family','006-dog','011-bear','013-cow','015-horse','016-lion','023-car','027-plane','028-bike','031-cup','034-chair','037-door','040-phone','041-apple','044-berry','047-bread','051-head','053-nose','054-mouth','059-hair','061-shirt','065-hat','070-boots','073-star','076-snow','077-tree','083-yes','087-more','089-help','093-mad','095-hungry','096-big','099-cold'],
  poppy:['001-mommy','005-friend','007-cat','008-bird','012-bunny','014-pig','019-bug','020-butterfly','022-book','024-truck','026-boat','029-doll','033-plate','036-bath','039-clock','043-orange','046-water','049-egg','052-eyes','055-ears','056-hands','060-teeth','063-shoes','066-coat','067-dress','072-moon','075-rain','078-flower','080-sky','081-hi','084-no','086-thanks','090-love','092-sad','098-hot','100-gentle'],
  doodle:['003-baby','009-fish','010-duck','017-monkey','018-frog','021-ball','025-train','030-blocks','032-spoon','035-bed','038-light','042-banana','045-milk','048-cheese','050-cookie','057-feet','058-tummy','062-pants','064-socks','068-pajamas','069-diaper','071-sun','074-cloud','079-grass','082-bye','085-please','088-all-done','091-happy','094-sleepy','097-little']
};
const WORD_AUDIO=Object.entries(WORD_AUDIO_GROUPS).flatMap(([voice,names])=>names.map(name=>`./audio/voice-packs/${voice}/words/${name}.mp3`));
const SPANISH_NUMBER_AUDIO={pip:['001-0','002-1','005-4','008-7','011-10'],poppy:['003-2','006-5','009-8'],doodle:['004-3','007-6','010-9']};
const SPANISH_LETTER_AUDIO={poppy:['001-a','004-d','006-f','007-g','008-h','009-i','014-n','015-n','024-w','027-z'],doodle:['002-b','010-j','017-p','018-q','019-r','020-s','021-t','025-x'],pip:['003-c','005-e','011-k','012-l','013-m','016-o','022-u','023-v','026-y']};
const SPANISH_COLOR_AUDIO=['red','orange','yellow','pink','purple','green','blue','black','brown'].map((color,index)=>`./audio/voice-packs-es/doodle/colors-es/${String(index+1).padStart(3,'0')}-${color}.mp3`);
const SPANISH_SHAPE_AUDIO={doodle:['001-circle','004-rectangle','007-star'],pip:['002-square','005-oval','008-heart'],poppy:['003-triangle','006-diamond','009-crescent']};
const voiceFiles=(groups,category)=>Object.entries(groups).flatMap(([voice,names])=>names.map(name=>`./audio/voice-packs-es/${voice}/${category}/${name}.mp3`));
const SPANISH_NUMBER_AUDIO_FILES=voiceFiles(SPANISH_NUMBER_AUDIO,'numbers-es');
const SPANISH_LETTER_AUDIO_FILES=voiceFiles(SPANISH_LETTER_AUDIO,'letters-es');
const SPANISH_SHAPE_AUDIO_FILES=voiceFiles(SPANISH_SHAPE_AUDIO,'shapes-es');
const SPANISH_WORD_AUDIO=Object.entries(WORD_AUDIO_GROUPS).flatMap(([voice,names])=>names.map(name=>`./audio/voice-packs-es/${voice}/words-es/${name}.mp3`));
const LOCAL=['./','./index.html','./styles.css','./data.js','./app.js','./manifest.webmanifest','./assets/meadow-pals/app-icon.png','./assets/meadow-pals/meadow-pals.png','./assets/meadow-pals/numbers/0-empty-basket.png','./assets/meadow-pals/numbers/1-apple.png','./assets/meadow-pals/numbers/2-birds.png','./assets/meadow-pals/numbers/3-ducklings.png','./assets/meadow-pals/numbers/4-blocks.png','./assets/meadow-pals/numbers/5-flowers.png','./assets/meadow-pals/numbers/6-bubbles.png','./assets/meadow-pals/numbers/7-strawberries.png','./assets/meadow-pals/numbers/8-balloons.png','./assets/meadow-pals/numbers/9-balls.png','./assets/meadow-pals/numbers/10-stars.png','./audio/voice-packs/pip/numbers/001-0.mp3','./audio/voice-packs/pip/numbers/002-1.mp3','./audio/voice-packs/poppy/numbers/003-2.mp3','./audio/voice-packs/doodle/numbers/004-3.mp3','./audio/voice-packs/pip/numbers/005-4.mp3','./audio/voice-packs/poppy/numbers/006-5.mp3','./audio/voice-packs/doodle/numbers/007-6.mp3','./audio/voice-packs/pip/numbers/008-7.mp3','./audio/voice-packs/poppy/numbers/009-8.mp3','./audio/voice-packs/doodle/numbers/010-9.mp3','./audio/voice-packs/pip/numbers/011-10.mp3','./audio/meadow-pals/calm-playtime.mp3','./audio/meadow-pals/cozy-lullaby.mp3','./audio/meadow-pals/little-steps.mp3','./audio/meadow-pals/sweet-kindergarten.mp3',...LETTER_AUDIO,...COLOR_AUDIO,...SHAPE_AUDIO_FILES,...SPANISH_NUMBER_AUDIO_FILES,...SPANISH_LETTER_AUDIO_FILES,...SPANISH_COLOR_AUDIO,...SPANISH_SHAPE_AUDIO_FILES,...LETTER_ART,...COLOR_ART,...SHAPE_ART,...SPANISH_LETTER_ART,...WORD_AUDIO,...SPANISH_WORD_AUDIO,...BODY_PART_ART,...ANIMAL_ART,...FOOD_ART,...FEELINGS_ART,...PEOPLE_ART,...THINGS_ART,...PLAY_ART,...NATURE_ART,...SOCIAL_ART,...HOME_ART,...CLOTHING_ART];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(LOCAL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(fetch(event.request).then(response=>{if(new URL(event.request.url).origin===self.location.origin){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>caches.match(event.request).then(hit=>hit||caches.match('./index.html'))))});
